refactor on dtos
Hepsiburada-Backend-Bootcamp/Homework-4-te-4 pull request #11
Opened 2021-10-20 13:25 UTC by cagdem

2021-10-21 20:44 UTC, alprsln requested changes
Domaindeki dtolar süper olmuş, fakat dtoları application'dan kaldırdıktan sonra mergelesek daha iyi olur. 😃

2021-10-22 14:40 UTC, alprsln approved these changes
Ellerine sağlık. 🙂

2021-10-22 16:00 UTC, mesadunal approved these changes

2021-10-22 16:03 UTC, cnsuKahveci approved these changes

2021-10-22 16:17 UTC, merged